AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 5

Resources:

    LeerEventoDynamoDB:
        Type: AWS::Serverless::Function 
        Properties:
            Architectures:
                 - x86_64
            CodeUri: ./lambda
            Handler: aplicacion.manejador
            Runtime: python3.10
            Policies:
                - AmazonDynamoDBReadOnlyAccess
            Events:
                DynamoDBEvent:
                    Type: DynamoDB 
                    Properties:
                        Stream:
                            !GetAtt DynamoDBTable.StreamArn
                        StartingPosition: TRIM_HORIZON
                        BatchSize: 10

    DynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            ProvisionedThroughput:
                WriteCapacityUnits: 5
                ReadCapacityUnits: 5
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - KeyType: HASH
                  AttributeName: id
