version: 0.2
phases:
  build:
    commands:
       - aws cloudformation package --template-file app-sam.yaml --output-template-file packaged.yaml --s3-bucket codebuild-jevs-us-east-1
artifacts:
  files:
    - packaged.yaml